[build]
  command = 'npm run build'
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/404"
  to = "/"
  status = 302

[context.production.environment]
  GATSBY_API_URL="https://api.cybercomcreation.com/"

[context.environment]
 GATSBY_API_URL="https://api.cybercomcreation.com/"
